name: thesis
dependencies:
    - pytorch
    - torchvision
    # - cudatoolkit=10.0
    - matplotlib
    - pretty_midi
    - python
    - pylint
    - scipy
    - pixiedust
channels:
    - pytorch
    - conda-forge
    - defaults
    - roebel