name: thesis
dependencies:
    - pytorch
    - torchvision
    - cudatoolkit=10.2
    - matplotlib
    - pretty_midi
    - python
    - pylint
    - scipy
    - pixiedust
    - music21
    - neptune-client
    - neptune-notebooks
    - nodejs
    - jupyterlab
    - psutil
channels:
    - pytorch
    - anaconda
    - conda-forge
    - defaults
    - roebel
    - iainsgillis