name: thesis
dependencies:
    - pytorch=1.1.0
    - torchvision=0.3.0
    - cudatoolkit=10.0
    - matplotlib
    - pretty_midi
    - python=3.6
    - pylint
    - scipy
channels:
    - pytorch
    - conda-forge
    - defaults
    - roebel